# Generated by Django 6.0.2 on 2026-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ridge_length',
        ),
        migrations.RemoveField(
            model_name='project',
            name='valley_length',
        ),
        migrations.AddField(
            model_name='project',
            name='dump_fee',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='project',
            name='waste_percentage',
            field=models.FloatField(default=10.0),
        ),
    ]
